name: Checks and Validation
on:
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: clippy,rustfmt
          targets: wasm32-unknown-unknown

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: 'linter_cache'
      - uses: bahmutov/npm-install@v1

      - name: Run linters
        uses: profiidev/rust-lint-action@d3a5a7ebf7efe08148b1b9bb02231b0b03934f22 # v4
        with:
          rustfmt: true
          clippy: true
          auto_fix: true
          oxfmt: true
          clippy_args: --target wasm32-unknown-unknown
